// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq8fxf8uOKivhG7U-GIIqtKr-CKx57yow',
    appId: '1:514230005785:web:49b059ed2245698e69ba88',
    messagingSenderId: '514230005785',
    projectId: 'uasflutter-d5b37',
    authDomain: 'uasflutter-d5b37.firebaseapp.com',
    storageBucket: 'uasflutter-d5b37.appspot.com',
    measurementId: 'G-G0EKMLDXVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseyDKRCgy32kc7pqaG6wBpMBQl00pJDQ',
    appId: '1:514230005785:android:f9ab006aa0e82ee869ba88',
    messagingSenderId: '514230005785',
    projectId: 'uasflutter-d5b37',
    storageBucket: 'uasflutter-d5b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJc4zlZW-DxVUvcxZKtCF0PxyHNL1qiHc',
    appId: '1:514230005785:ios:23ff74dd61b283d469ba88',
    messagingSenderId: '514230005785',
    projectId: 'uasflutter-d5b37',
    storageBucket: 'uasflutter-d5b37.appspot.com',
    iosBundleId: 'com.example.uasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJc4zlZW-DxVUvcxZKtCF0PxyHNL1qiHc',
    appId: '1:514230005785:ios:34837ff30617ca9c69ba88',
    messagingSenderId: '514230005785',
    projectId: 'uasflutter-d5b37',
    storageBucket: 'uasflutter-d5b37.appspot.com',
    iosBundleId: 'com.example.uasFlutter.RunnerTests',
  );
}
